---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverless-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverless-redis
  template:
    metadata:
      labels:
        app: serverless-redis
    spec:
      containers:
      - name: serverless-redis
        image: albatis/serverless-runtime:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: zip-volume
          mountPath: "/opt/function_code/metrics_function.zip"
          subPath: metrics_function.zip
        env:
        - name: CODE_ZIP_PATH
          value: "/opt/function_code/metrics_function.zip"
        - name: HANDLER_ENTRYPOINT
          value: "metrics_processor.handler.complex_handler"
        - name: REDIS_MONITOR_PERIOD
          value: "5"
        - name: REDIS_HOST
          value: "192.168.121.171"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_INPUT_KEY
          value: "metrics"
        - name: REDIS_OUTPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: outputkey
              key: REDIS_OUTPUT_KEY
      volumes:
      - name: zip-volume
        configMap:
          name: metrics-function-zip
          items:
          - key: metrics_function.zip
            path: metrics_function.zip