serverless:
  name: serverless
  login: alexandrevieira
  image: lucasmsp/serverless:redis
  replicas: 1
  containerPort: 80
  servicePort: 8080
  nodePort: 50100
  resources:
    memory: 2Gi
  files:
    hello.py: |-
      print("Hello, world!")
  