serverless:
  name: serverless
  login: alexandrevieira
  image: nginx:latest
  replicas: 1
  containerPort: 80
  servicePort: 8080
  nodePort: 50100
  resources:
    memory: 32Mi
  files:
    hello.py: |-
      print("Hello, world!")
  